### ISSUE TITLE
No family tree

### ISSUE THREAD

**Issue by wanyingzhang** [Ileezyy/dsfd-assignment3#1]
When I tried to open website on my local machine, I couldn't find "family tree" on the screen. I double checked the code, and it seems to be fine. 

<img width="1440" alt="2017-11-29 17 44 13" src="https://user-images.githubusercontent.com/33317728/33390257-4a2a7dd6-d52d-11e7-849b-fed2131cfd54.png">

Because on actual website there is Family tree.

<img width="1440" alt="2017-11-29 17 47 57" src="https://user-images.githubusercontent.com/33317728/33390320-760b95e8-d52d-11e7-842d-75c3c0e7828d.png">

What's the matter?

**Comment by Ileezyy** [comment]
What are you using on your local machine? I mean is there any server? Or you are just running website by opening index.html directly?

**Comment by wanyingzhang** [comment]
Yes i‘ve run it directly by doubling click index.html

**Comment by Hug0L1u** [comment]
what's your system? I also have this issue actually

**Comment by Ileezyy** [comment]
OK. I see. So, to run a local server on **Mac** you can just go to the folder (e.g. `cd dsdf-assignment3/public`) and then run following command: `python3 -m http.server`. 
NOTE: you have to have pre-installed `python3` for that.

And if you use **Windows** OS, then you should install some software, such as **XAMPP**.
Basically, it can be installed both on Mac OS and Windows OS.

Hope it helps.
